'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ActionEvent, type DataCardCustomEvent } from "@kit-data-manager/data-view-web-component";
import { DataCard as DataCardElement, defineCustomElement as defineDataCard } from "@kit-data-manager/data-view-web-component/dist/components/data-card.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type DataCardEvents = { onActionClick: EventName<DataCardCustomEvent<ActionEvent>> };

export const DataCard: StencilReactComponent<DataCardElement, DataCardEvents> = /*@__PURE__*/ createComponent<DataCardElement, DataCardEvents>({
    tagName: 'data-card',
    elementClass: DataCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onActionClick: 'actionClick' } as DataCardEvents,
    defineCustomElement: defineDataCard
});
