/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ActionEvent, type DataCardCustomEvent } from "@kit-data-manager/data-view-web-component";
import { DataCard as DataCardElement, defineCustomElement as defineDataCard } from "@kit-data-manager/data-view-web-component/dist/components/data-card.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import React from 'react';

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type DataCardEvents = { onActionClick: EventName<DataCardCustomEvent<ActionEvent>> };

export const DataCard: StencilReactComponent<DataCardElement, DataCardEvents> = /*@__PURE__*/ createComponent<DataCardElement, DataCardEvents>({
    tagName: 'data-card',
    properties: {
        imageUrl: 'image-url',
        dataTitle: 'data-title',
        subTitle: 'sub-title',
        bodyText: 'body-text',
        textRight: 'text-right',
        actionButtons: 'action-buttons',
        tags: 'tags',
        childrenData: 'children-data',
        childrenLabel: 'children-label',
        metadata: 'metadata',
        variant: 'variant',
        childrenVariant: 'children-variant',
        nested: 'nested'
    },
    hydrateModule: import('@kit-data-manager/data-view-web-component/hydrate') as Promise<HydrateModule>,
    serializeShadowRoot,
    elementClass: DataCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onActionClick: 'actionClick' } as DataCardEvents,
    defineCustomElement: defineDataCard
});
