/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Tag, TextPropType, ValueLabelObj, ValueLabelObjWithUrl } from "./components/data-card/data-card-types";
export { Tag, TextPropType, ValueLabelObj, ValueLabelObjWithUrl } from "./components/data-card/data-card-types";
export namespace Components {
    interface DataCard {
        "bodyText": TextPropType;
        "dataTitle": TextPropType;
        "imageUrl"?: string;
        "metadata": Array<ValueLabelObj | ValueLabelObjWithUrl>;
        "subTitle": TextPropType;
        "tags": Array<Tag>;
        "textRight": TextPropType;
        "variant": 'default' | 'detailed' | 'minimal';
    }
}
declare global {
    interface HTMLDataCardElement extends Components.DataCard, HTMLStencilElement {
    }
    var HTMLDataCardElement: {
        prototype: HTMLDataCardElement;
        new (): HTMLDataCardElement;
    };
    interface HTMLElementTagNameMap {
        "data-card": HTMLDataCardElement;
    }
}
declare namespace LocalJSX {
    interface DataCard {
        "bodyText"?: TextPropType;
        "dataTitle"?: TextPropType;
        "imageUrl"?: string;
        "metadata"?: Array<ValueLabelObj | ValueLabelObjWithUrl>;
        "subTitle"?: TextPropType;
        "tags"?: Array<Tag>;
        "textRight"?: TextPropType;
        "variant"?: 'default' | 'detailed' | 'minimal';
    }
    interface IntrinsicElements {
        "data-card": DataCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "data-card": LocalJSX.DataCard & JSXBase.HTMLAttributes<HTMLDataCardElement>;
        }
    }
}
