/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActionButtonInterface, ActionEvent, Tag, TextPropType, ValueLabelObj, ValueLabelObjWithUrl } from "./components/data-card/data-card-types";
export { ActionButtonInterface, ActionEvent, Tag, TextPropType, ValueLabelObj, ValueLabelObjWithUrl } from "./components/data-card/data-card-types";
export namespace Components {
    interface DataCard {
        /**
          * Array of action buttons to be displayed on the card
         */
        "actionButtons"?: Array<ActionButtonInterface> | string;
        /**
          * Body text of the card
         */
        "bodyText"?: TextPropType;
        /**
          * Array of children cards to be displayed on the card
         */
        "childrenData"?: Array<DataCard> | string;
        /**
          * Clickable label to display when the card has children
         */
        "childrenLabel"?: string;
        /**
          * Title of the card
         */
        "dataTitle": TextPropType;
        /**
          * URL of the image to be displayed on the card
         */
        "imageUrl"?: string;
        /**
          * Array of metadata to be displayed on the card in the detailed view
         */
        "metadata"?: Array<ValueLabelObj | ValueLabelObjWithUrl> | string;
        /**
          * Whether the card is being used inside of the detailed view
         */
        "nested": boolean;
        /**
          * Subtitle of the card
         */
        "subTitle"?: TextPropType;
        /**
          * Array of tags to be displayed on the card
         */
        "tags"?: Array<Tag> | string;
        /**
          * Text to be displayed on the right of the card
         */
        "textRight"?: TextPropType;
        /**
          * Variant of the card
         */
        "variant"?: 'default' | 'detailed' | 'minimal';
    }
}
export interface DataCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDataCardElement;
}
declare global {
    interface HTMLDataCardElementEventMap {
        "actionClick": ActionEvent;
    }
    interface HTMLDataCardElement extends Components.DataCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDataCardElementEventMap>(type: K, listener: (this: HTMLDataCardElement, ev: DataCardCustomEvent<HTMLDataCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDataCardElementEventMap>(type: K, listener: (this: HTMLDataCardElement, ev: DataCardCustomEvent<HTMLDataCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDataCardElement: {
        prototype: HTMLDataCardElement;
        new (): HTMLDataCardElement;
    };
    interface HTMLElementTagNameMap {
        "data-card": HTMLDataCardElement;
    }
}
declare namespace LocalJSX {
    interface DataCard {
        /**
          * Array of action buttons to be displayed on the card
         */
        "actionButtons"?: Array<ActionButtonInterface> | string;
        /**
          * Body text of the card
         */
        "bodyText"?: TextPropType;
        /**
          * Array of children cards to be displayed on the card
         */
        "childrenData"?: Array<DataCard> | string;
        /**
          * Clickable label to display when the card has children
         */
        "childrenLabel"?: string;
        /**
          * Title of the card
         */
        "dataTitle"?: TextPropType;
        /**
          * URL of the image to be displayed on the card
         */
        "imageUrl"?: string;
        /**
          * Array of metadata to be displayed on the card in the detailed view
         */
        "metadata"?: Array<ValueLabelObj | ValueLabelObjWithUrl> | string;
        /**
          * Whether the card is being used inside of the detailed view
         */
        "nested"?: boolean;
        /**
          * Event emitted when an action button is clicked
         */
        "onActionClick"?: (event: DataCardCustomEvent<ActionEvent>) => void;
        /**
          * Subtitle of the card
         */
        "subTitle"?: TextPropType;
        /**
          * Array of tags to be displayed on the card
         */
        "tags"?: Array<Tag> | string;
        /**
          * Text to be displayed on the right of the card
         */
        "textRight"?: TextPropType;
        /**
          * Variant of the card
         */
        "variant"?: 'default' | 'detailed' | 'minimal';
    }
    interface IntrinsicElements {
        "data-card": DataCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "data-card": LocalJSX.DataCard & JSXBase.HTMLAttributes<HTMLDataCardElement>;
        }
    }
}
