# Derived from: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Node.js Package to npmjs.com
on:
  release:
    types: [ published ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - run: |
          npm clean-install
          npm run build
          npm publish --access public
          cd react-library
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
