# Derived from: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Node.js Package to npmjs.com
on:
  release:
    types: [ published ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - name: Publish component
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish react-wrapper
        run: |
          cd react-library
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
